name: meanfrontend

on:
  push:
    branches:
      - main

jobs:
  frontendd:
    runs-on: ubuntu-latest
    steps:
      - name: get code from git
        uses: actions/checkout@v4
      - name: connect
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{secrets.IP}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.MEAN}}

          script: |
            cd /home/ubuntu/mean-frontend
            docker build -t frontend .
            docker run -d -p 4200:4200 frontend
          
